[project]
name = "Music-Recommender-System"
version = "0.1.0"
description = "A chatbot that recommends music based on user preferences."
readme = "README.md"
requires-python = ">=3.9"

[tool.pytest.ini_options]
pythonpath = "musicCRS"
